heat_template_version: 2014-10-16

description: Template to deploy 2 instances on FutureSystems

resources:
  secgroup:
    type: OS::Neutron::SecurityGroup
    properties:
      rules:
        - protocol: tcp
          remote_ip_prefix: 0.0.0.0/0
          port_range_min: 22
          port_range_max: 22
        - protocol: tcp
          remote_ip_prefix: 0.0.0.0/0
          port_range_min: 80
          port_range_max: 80
        - protocol: tcp
          remote_ip_prefix: 0.0.0.0/0
          port_range_min: 443
          port_range_max: 443

  instance_port1:
    type: OS::Neutron::Port
    properties:
      network: int-net
      security_groups:
        - default
        - { get_resource: secgroup }

  instance_port2:
    type: OS::Neutron::Port
    properties:
      network: int-net
      security_groups:
        - default
        - { get_resource: secgroup }

  my_instance1:
    type: OS::Nova::Server
    properties:
      key_name: rabindra-key
      image: futuresystems/ubuntu-14.04
      flavor: m1.small
      networks:
        - port: {get_resource: instance_port1}

  my_instance2:
    type: OS::Nova::Server
    depends_on: [ my_instance1 ]
    properties:
      key_name: rabindra-key
      image: futuresystems/ubuntu-14.04
      flavor: m1.small
      networks:
        - port: {get_resource: instance_port2}

