---
- hosts: ansible-test
  remote_user: ubuntu
  tasks:
  - name: Import the public key used by the package management system
    apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=7F0CEB10 state=present
  - name: Add MongoDB repository
    apt_repository: repo='deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' state=present
  - name: Install mongodb
    apt: pkg=mongodb-org state=latest update_cache=yes
    notify:
    - start mongodb
  - name: Download data file
    get_url: url=https://s3.amazonaws.com/open_data/csv/opendata_projects.zip dest=/home/ubuntu/VisualizationProject/ mode=0440
  - name: Install unzip
    apt: pkg=unzip state=latest update_cache=yes
  - name: Unzip project data
    command: 'unzip /home/ubuntu/VisualizationProject/opendata_projects.zip'
  - name: Load data into mongdb
    command: 'mongoimport -d donorschoose -c projects --type csv --file opendata_projects.csv -headerline'
  handlers:
    - name: start mongodb
      service: name=mongod state=started
