---
- hosts: ansible-test
  remote_user: ubuntu
  sudo: yes
  tasks:
  - name : Download ezsetup
    get_url: url=https://bootstrap.pypa.io/ez_setup.py dest=~/ mode=777
  - name : Execute script
    command : 'python ~/ez_setup.py'
  - name : Install pip
    command : 'easy_install pip'
  - name : Install virtualenv
    command : 'pip install virtualenv'
  - name : Create a virtual environment
    command : '/usr/local/bin/virtualenv /home/ubuntu/ENV'
  - name : Activate virtual environment
    command : 'source /home/ubuntu/ENV/bin/activate'
  - name : Install cloudmesh
    pip : name=cloudmesh_base 
  - name : Install cmd3
    pip : name=cmd3 
  - name : Install git
    apt : name=git
  - name : Copy project repo contents
    git : repo=https://github.com/futuresystems/465-rahulbindra
          dest=/home/ubuntu/465-rahulbindra
  - name : Change permissions for main python file
    command : 'chmod 777 /home/ubuntu/465-rahulbindra/VisualizationProject/app.py'
  - name : Install Flask
    pip : name=Flask virtualenv='~/ENV'
  - name : Install pymongo
    pip : name=pymongo virtualenv='~/ENV'
