---
- hosts: ansible-test
  remote_user: ubuntu
  tasks:
  - name : Download ezsetup
    get_url: url=https://bootstrap.pypa.io/ez_setup.py dest=~/ mode=0777
  - name : Execute script
    command : 'sudo python ~/ez_setup.py'
  - name : Install pip
    command : 'sudo easy_install pip'
  - name : Install virtualenv
    command : 'sudo pip install virtualenv'
  - name : Create a virtual environment
    command : '/usr/local/bin/virtualenv /home/ubuntu/ENV'
  - name : Install cloudmesh
    pip : name=cloudmesh_base virtualenv='~/ENV'
  - name : Install cmd3
    pip : name=cmd3 virtualenv='~/ENV'
  - name : Install git
    command : 'sudo apt-get install git'
  - name : Copy project repo contents
    git : repo=https://github.com/futuresystems/465-rahulbindra
          dest=/home/ubuntu/VisualizationProject
  - name : Change permissions for main python file
    command : 'sudo chmod 777 /home/ubuntu/VisualizationProject/app.py'
  - name : Install Flask
    pip : name=Flask virtualenv='~/ENV'
